// <auto-generated />
using ASP.NET_Core_Empty_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NET_Core_Empty_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP.NET_Core_Empty_Project.Models.PersonDb", b =>
                {
                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSN");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            SSN = "19890209-1234",
                            Name = "Albin de Val",
                            PhoneNr = "0721222324"
                        },
                        new
                        {
                            SSN = "19700707-4321",
                            Name = "Håkan Svensson",
                            PhoneNr = "031555666777"
                        },
                        new
                        {
                            SSN = "19801010-4125",
                            Name = "Anders Andersson",
                            PhoneNr = "1234567"
                        },
                        new
                        {
                            SSN = "20000909-0909",
                            Name = "Max Verstappen",
                            PhoneNr = "528582685"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
